util:
  count-of-random-uri-characters: 6

http:
  url: http://localhost:8080/

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration: 86400000 # a day
  refresh-expiration: 604800000

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger/ui

#  show-login-endpoint: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortlink
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      additional-paths: src/main/java/com/shortlink/webapp
      enabled: true

  messages:
    basename: i18n/messages

  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql

    properties:
      hibernate:
        format_sql: true
        #        hbm2ddl.auto: create
        hbm2ddl.auto: validate
        jdbc:
          time_zone: UTC

      org:
        hibernate:
          envers:
            store_data_at_delete: true
            audit_table_suffix: _audit
            revision_field_name: revision_id
    #            autoRegisterListeners: false
    #            global_prefix: audit_
    #            audit_strategy_validity_store_revend_timestamp_field_name: change_type
    #            audit_strategy: org.hibernate.envers.DefaultAuditStrategy


    #    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #    hibernate:
  #      ddl-auto: validate



  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml


