#  docker run -d --name redis -p 6379:6379 redis redis-server --save 20 1 --loglevel warning --requirepass 12345
#  docker run -d -p 9000:9000 -p 9001:9001 --name minio minio/minio server /data --console-address ":9001"

#  docker run -d --name redis -p 6379:6379 -p 8001:8001 redislabs/redis:latest --requirepass your_password

minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin
  bucket: images

link:
  count-of-random-url-characters: 6

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration: 86400000 # a day
  refresh-expiration: 604800000

token:
  verify-email-expiration: 10
  reset-password-expiration: 10


server:
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /swagger/ui

#  show-login-endpoint: true
spring:
  profiles:
    active:
#      - test
#      - prod
      - dev

  cache:
    type: redis
    cache-names: redis-cache
#    redis:
#      time-to-live: 100000

  data:
    redis:
      host: localhost
      port: 6379
      password: 12345

#  mvc:
#    format:
#      date-time: iso
#      date: iso
#      time: iso

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://localhost:5432/shortlink?currentSchema=shortlink
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      additional-paths: src/main/java/com/shortlink/webapp
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: liroy2468@gmail.com
    password: qsff wehe ndqj slbb

    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  #  messages:
#    basename: i18n/messages
#    encoding: UTF-8

  liquibase:
    enabled: true
#    enabled: false
    change-log: db/changelog/db.changelog-master.yml
    default-schema: shortlink

  jpa:
    open-in-view: false
    database: postgresql

    properties:
      hibernate:
#        enable_lazy_load_no_trans: true

        show_sql: true
        format_sql: true
#        hbm2ddl.auto: create
        hbm2ddl.auto: validate
        fetch_size: 50
        batch_size: 50
        default_schema: shortlink
#        jdbc:
#          time_zone: UTC

      org:
        hibernate:
          envers:
            store_data_at_delete: true
            audit_table_suffix: _audit
            revision_field_name: revision_id
#            revision_type_field_name:

logging:
  level:
    org.springframework.cache: TRACE
#logging:
#  level:
#    root: info
#    sql: info

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        data:
#          redis:
#            cache:
#              RedisCacheManager: TRACE
#
#
#
#            core:
#              RedisTemplate: TRACE