minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin
  bucket: images

link:
  count-of-random-url-characters: 8

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration: 86400000 # a day
  refresh-expiration: 604800000

token:
  verify-email-expiration: 10
  reset-password-expiration: 10

server:
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /swagger/ui

#  show-login-endpoint: true
spring:
  profiles:
    active:
#      - test
#      - prod
      - dev
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso

  datasource:
    url: jdbc:postgresql://localhost:5432/shortlink?currentSchema=shortlink
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      additional-paths: src/main/java/com/shortlink/webapp
      enabled: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: liroy2468@gmail.com
    password: qsff wehe ndqj slbb

    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  #  messages:
#    basename: i18n/messages
#    encoding: UTF-8

  liquibase:
    enabled: true
#    enabled: false
    change-log: db/changelog/db.changelog-master.yml
    default-schema: shortlink

  jpa:
    open-in-view: false
    database: postgresql

    properties:
      hibernate:
#        enable_lazy_load_no_trans: true

        show_sql: true
        format_sql: true
#        hbm2ddl.auto: create
        hbm2ddl.auto: validate
        fetch_size: 50
        batch_size: 50
        default_schema: shortlink

      #        jdbc:
#          time_zone: UTC

      org:
        hibernate:
          envers:
            store_data_at_delete: true
            audit_table_suffix: _audit
            revision_field_name: revision_id
#            revision_type_field_name:

#logging:
#  level:
#    root: info
#    sql: info

#logging:
#  level:
#    root: INFO
#    org.springframework.jdbc.core: TRACE
